### ISSUE TITLE
Latest release tarball not available

### ISSUE THREAD

**Issue by javsalgar** [containerd/cri#1061]
I am following the instructions here: https://github.com/containerd/cri/blob/master/docs/installation.md

I see that the latest version available is 1.11.1. However, the latest available tarball is around 1.2 approximately. 

Am I missing something?

**Comment by estesp** [comment]
I'm not sure what you mean about the latest version is 1.11.1. The CRI implementation for containerd is aligned with containerd releases since early last year; so [1.2.4](https://github.com/containerd/containerd/releases) is the latest containerd release, and contains the latest CRI plugin for Kubernetes, which works with versions 1.11.x, 1.12.x, 1.13.x, etc. of Kubernetes.

**Comment by mikebrow** [comment]
wget https://storage.googleapis.com/cri-containerd-release/cri-containerd-cni-1.2.4.linux-amd64.tar.gz

works here...

**Comment by mikebrow** [comment]
We have a table that maps the kubernetes integration support to containerd/cri version:

https://github.com/containerd/cri#support-metrics

**Comment by mikebrow** [comment]
oh .. I see the issue I think..

We have a confusing version label for the plugin repo..  Probably need to explain that in the instructions and cri/releases so it's understood which version of containerd said plugin's correspond with.. and to make sure they know they are pulling down the corresponding version of containerd to get the plugin... also the naming cri-containerd is a misnomer since it's really containerd with cri..

**Comment by Random-Liu** [comment]
In the doc, we mentioned that "For each containerd release, we'll publish a release tarball specifically for Kubernetes named cri-containerd-${VERSION}.${OS}-${ARCH}.tar.gz."

We may need to make it more clear. @mikebrow Would you like to send an update to the document?

**Comment by mikebrow** [comment]
sure!

**Comment by carlosedp** [comment]
I believe @javsalgar question is because the cri repo doesn't contain git tags for each version.

This makes a hard to build a specific release version of cri for the latest stable version on the version cut.

**Comment by estesp** [comment]
I guess it is up to the CRI repository owners if they want to add matching release tags, but it would be pretty reasonable to just take any containerd release tag (from the `containerd/containerd` GH project), grep that release's copy of `vendor.conf` for `github.com/container/cri`; that will give the exact commit hash of the cri project that was used in that release, which can then be checked out in a clone of this cri project if you are wanting to work in context of this repo.

**Comment by MarkusTeufelberger** [comment]
https://github.com/containerd/cri/releases lists 1.11.1 as the latest version.

**Comment by Random-Liu** [comment]
I think this should have been fixed.
