### ISSUE TITLE
Consider using / checking for changes to PodSandboxConfig

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#1062]
PullImage(image *runtimeapi.ImageSpec, auth *runtimeapi.AuthConfig, ***_podSandboxConfig _runtimeapi.PodSandboxConfig**__) (string, error)

Since podSandboxConfig *runtimeapi.PodSandboxConfig was added above in cri api.. we had to add that to our integration tests that call pullimage. 

We should find out why it was added and start "using it" if there was a scenario where we don't use the pod's original podsandboxconfig. Possibly add some test cases.

This is an issue to investigate why the change was made so we can address the change in a meaningful way.

**Comment by Random-Liu** [comment]
> We should find out why it was added and start "using it" if there was a scenario where we don't use the pod's original podsandboxconfig. Possibly add some test cases.

The change was made because 1) we have `podSandboxConfig` in the `PullImageRequest` since the beginning, we just didn't set it in Kubelet; 2) This is useful for some case where image is pulled and managed per sandbox box, e.g. someone run a PodSandbox as a remote VM.

I don't think we need to do anything in containerd/cri right now for this field. We can add the support in the future, when we started working on those use cases.

**Comment by jterry75** [comment]
@mikebrow - We use this for the Windows RuntimeHandler's because there is no other facility to describe what platform an image should be pulled for. On Windows our runtime supports Windows/Linux containers so we are currently using a custom annotation in the PodSandboxConfig to describe this. But with that said, I believe the proper solution is that the `ImageSpec` contains the `Platform, Arch` flags like `OCI` and we wouldn't need this config anymore.
