### ISSUE TITLE
Should we remove trusted/untrusted runtime references from the code?

### ISSUE THREAD

**Issue by sboeuf** [containerd/cri#1095]
The `RuntimeClass` is now a well known and supported feature in k8s, hence I was wondering if we could simplify the code picking the right container runtime by removing the references to `trusted`/`untrusted` (mainly [here](https://github.com/containerd/cri/blob/master/pkg/server/sandbox_run.go)).

**Comment by mikebrow** [comment]
The deprecation occurred in the containerd 1.2 release on October 24, 2018 with the following release notice:
```The plugins.cri.containerd.untrusted_workload_runtime config option and io.kubernetes.cri.untrusted-workload pod annotation are still functional, but start being deprecated. It is recommended to migrate to the RuntimeClass api.```

The CRI API is considered unstable with respect to the issue of whether deprecated content will be supported. However, since this should be easy to maintain we should probably follow the containerd policy https://github.com/containerd/containerd/blob/master/RELEASES.md and support backwards compatibility for one major release, which would be 1.3. I would suggest tagging this issue as a 1.4 release item.

**Comment by tallclair** [comment]
> The RuntimeClass is now a well known and supported feature in k8s

RuntimeClass went to beta with k8s 1.14. I don't think the untrusted references should be removed as long as that containerd version might be used with k8s < v1.14.

**Comment by sboeuf** [comment]
Ok so I guess it's a matter of choosing when to remove those references. As suggested by @mikebrow, it could be targeted that 1.4 will have those references removed. I'd assume that 1.4 would never run with k8s version < 1.14, right?

@tallclair wdyt?

**Comment by Random-Liu** [comment]
I added deprecation policy for config options at https://github.com/containerd/cri/pull/1125.

However, the untrusted annotation support is an API/feature change instead of config change, it may need longer time to deprecate. https://kubernetes.io/docs/reference/using-api/deprecation-policy/ doesn't define a deprecation time for annotation based apis.
