### ISSUE TITLE
masked and readonly paths doesn't work with k8s's procMount

### ISSUE THREAD

**Issue by choury** [containerd/cri#1208]
As the [code](https://github.com/kubernetes/kubernetes/blob/v1.15.1/pkg/securitycontext/util.go#L204) in kubernetes, kubelet will set empty masked and readonly paths if `procMount` is set.
But as a gRPC server, cri plugin will get nil field of the two paths.
ref: #894 
So, `procMount` will not work if containerd act as runtime of k8s.

**Comment by Random-Liu** [comment]
@choury gRPC server converts empty string to nil? That sounds like a bug to me... Let me see.

**Comment by Random-Liu** [comment]
Verified.

**Comment by Random-Liu** [comment]
It turns out that this is a complex issue... The issue is in the initial design of `MaskedPaths` and `ReadonlyPaths` in CRI. /cc @yujuhong @jessfraz 

Golang array corresponds to `repeated` field in protobuf. **In golang there is the difference between `nil` and empty array, but in protobuf both of them are empty repeated field.** This issue has been discussed several times e.g. https://github.com/gogo/protobuf/issues/181, https://github.com/kubernetes/kubernetes/issues/25835

* In Kubernetes 1.12 and later, empty `MaskedPaths` and `ReadonlyPaths` mean Kubelet wants to set masked path and readonly path empty.
* In Kubernetes 1.11 and before, `MaskedPaths` and `ReadonlyPaths` are always empty, because `ProcMount` is not supported yet, thus masked path and readonly path default should be applied.

**For the CRI plugin, there is no way to distinguish the 2 cases above.**

For this particular issue, the only solution we have is:
1) Set empty masked path and readonly path if `MaskedPaths` and `ReadonlyPaths` are empty;
2) Recommend users to use containerd 1.2 with Kubernetes 1.12+;
3) Add an `disable_proc_mount` option in the CRI plugin, so that when users use containerd 1.2 with Kubernetes 1.11 or below, they can disable the empty masked path and readonly path behavior.

**In the future, when we define new CRI array fields, if `Empty Array != runtime default`, we should wrap the `repeated` field with an `optional` message.**

**Comment by Random-Liu** [comment]
This is done. We'll include note about `disable_proc_mount` in the release note.
