### ISSUE TITLE
Can we run critest compliance in CI/CD?

### ISSUE THREAD

**Issue by jterry75** [containerd/cri#1370]
@Random-Liu, @mikebrow - Any reason we are not currently running critest against cri/containerd on PR for CI/CD? I actually though we were already doing this but turns out I was wrong.

**Comment by Random-Liu** [comment]
We are doing that.
For linux, it runs in travis.
For windows, it runs in pull-cri-containerd-windows-cri

**Comment by jterry75** [comment]
Thats what I thought. @PatrickLang - How did this break exactly?

**Comment by PatrickLang** [comment]
Hmm, I don't see any runs for the timeframe where it broke:
![image](https://user-images.githubusercontent.com/11345431/72029868-2a75a100-323c-11ea-9ef7-9280b2f325ab.png)

https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-cri-containerd-windows-cri

**Comment by PatrickLang** [comment]
yeah the PR that brought in the breaking change didn't run that test
https://github.com/containerd/cri/pull/1364

**Comment by Random-Liu** [comment]
@mikebrow we should make sure all presubmit tests pass before getting the change in :)

**Comment by mikebrow** [comment]
Could've sworn the PR was green, not sure why it would not have run pre-submits. I'll make sure they are included in the success list before putting a change in, otherwise yes we run the risk of having to revert.

On a side note I found some vndr discrepancies/changes between containerd and cri and pushed a PR for it. 

Also we had the windows presubmit gcloud connection down for few days.

**Comment by mikebrow** [comment]
oh.. I see what happened ... it never go the /ok-to-test
