### ISSUE TITLE
Being able to specify a containerd namespace

### ISSUE THREAD

**Issue by guilhem** [containerd/cri#1396]
Currently, the [containerd namespace](https://github.com/containerd/containerd/blob/master/docs/namespaces.md) is hard-coded `k8s.io`. https://github.com/containerd/cri/blob/0e42438e7a157f6aec41cd808a85bc883d646ff3/pkg/constants/constants.go#L23

To create a multi-tenancy Kubernetes cluster, we may have to specify this value, for example `k8scluster1`, `k8scluster2`…

**Comment by jterry75** [comment]
@Random-Liu - We could in theory use the `SandboxMetadata.Namespace` as a true namespace. But the issue with that is that the `PullImage` / `*Image` will also need to be namespace aware. It was my understanding that `k8s` is inherently not multi-tenant so that is why some of this doesn`t exist. Is that correct?

**Comment by dweomer** [comment]
I need this for [k3c](/rancher/k3c) and so I am working on a PR for it.

**Comment by mikebrow** [comment]
> @Random-Liu - We could in theory use the `SandboxMetadata.Namespace` as a true namespace. But the issue with that is that the `PullImage` / `*Image` will also need to be namespace aware. It was my understanding that `k8s` is inherently not multi-tenant so that is why some of this doesn`t exist. Is that correct?

Correct.

**Comment by mikebrow** [comment]
> I need this for [k3c](/rancher/k3c) and so I am working on a PR for it.

Are you proposing to draft code to introduce multi-tenancy into CRI or just to have the containerd namespace used by the CRI plugin be configurable in the cri config? 


If the former we should chat.

**Comment by dweomer** [comment]
> > @Random-Liu - We could in theory use the `SandboxMetadata.Namespace` as a true namespace. But the issue with that is that the `PullImage` / `*Image` will also need to be namespace aware. It was my understanding that `k8s` is inherently not multi-tenant so that is why some of this doesn`t exist. Is that correct?
> 
> Correct.

@mikebrow I am reading this as a word of caution, and I hear that, but I do need it for the k3c use-case as an underlying CRI impl for k3s (because I don't want to fork the kubelet) and so I've been working on a change-set to support what I am calling "managed" namespaces (aka containerd namespace's labelled with `io.cri-containerd=managed`) that CRI will control/service.

**Comment by dweomer** [comment]
> > I need this for [k3c](/rancher/k3c) and so I am working on a PR for it.
> 
> Are you proposing to draft code to introduce multi-tenancy into CRI or just to have the containerd namespace used by the CRI plugin be configurable in the cri config?
> 
> If the former we should chat.

In spirit, the latter. But as far as implementation it will act much like the former, I think.

**Comment by dweomer** [comment]
@mikebrow I am open to twitter DMs (if you follow me on twitter) or Zoom or what have you. I am also on keybase:
- https://twitter.com/dweomer
- https://keybase.io/dweomer

Email works as well.

**Comment by mikebrow** [comment]
@dweomer thanks for the chat... In the spirt of no forks needed, looking forward to seeing your changes.

**Comment by dweomer** [comment]
Pushed a WIP: #1462
