### ISSUE TITLE
cri-containerd failed to start when the number of containers is large

### ISSUE THREAD

**Issue by qiujian16** [containerd/cri#679]
I think we restarted kubelet/cri-containerd/containd several times, and then cri-container cannot be successfully started. We should have about 50 containers running on the node.  The log in cri-containerd shows that ```Error: failed to run cri-containerd grpc server: failed to recover state: failed to list containers: grpc: received message larger than max (4659741 vs. 4194304): unknown```

```ctr -n k8s.io container ls``` also return the similar error
```
ctr: grpc: received message larger than max (5003195 vs. 4194304): unknown
```

It seems that we are using the default 4M grpc response size, and it is not enough when the number of container is large.

**Comment by Random-Liu** [comment]
@qiujian16 Hm, we do have test running 100 pods, 200 containers on a node. I don't know why we didn't catch this.

If you have 50 containers on the node, it means that each container uses 80k? Is your container very complex? Are there a lot of annotations or labels?

Another question is that, we don't change the default MaxMsgSize in CRI as well. This may happen to Kubernetes CRI grpc interface as well. 

@stevvooe Should we change the max size limit? [MaxMsgSize](https://github.com/grpc/grpc-go/blob/2c2d834e8e13f239343a3441b76b0efcc167a0d7/server.go#L220)

**Comment by qiujian16** [comment]
@Random-Liu I cannot list all the containers for now...but since we restart kubelet/containerd several times, is it possible that there are many containers not in running state, so the total number of containers can be much larger than 50?

**Comment by Random-Liu** [comment]
@qiujian16 Restarting kubelet/containerd shouldn't restart the running containers. If it does, it is a bug.

Can you do this?
1) Check `/var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io` for container ids, to see how many containers are there.
2) Use `crictl inspect ${CONTAINERD_ID}` or `ctr --namespace=k8s.io c info ${CONTAINERD_ID}` to see how large is the container?

**Comment by Random-Liu** [comment]
The default max pod limit in Kubernetes is 110 today. Say we have 100 pods on a node, and 4 containers (including pause container) for each pod, then we'll have 400 containers on a node. Since the default message size limit is 4mb, we have 10k average size limit for each container.

Container metadata returned by containerd is larger because it contains runtime spec information and the metadata cri-containerd put on it as checkpoint.

Here is the size of the kube-proxy container metadata (~30k):
```console
$ ctr --namespace=k8s.io c info 3bef78b533df13d90c10f2e39faafc9d48d6696799a223
5873fc253588cb56b6 | wc -c
29877
```

Here is the size of a simple sandbox container (~4.6k):
```console
# ctr --namespace=k8s.io c info 8945fe343ea50bcb4b2d75c6001255a3b095b508b9c7c829c5d7424b3635c27a | wc -c
4837
```

Given so, I think it is not hard to hit the 4mb limit. I discussed this with @yujuhong as well, there are several options for this:
1) Set larger message size limit;
2) Return less information from `List` calls (e.g. only ids);
3) Use streaming;
4) Split result into pages.

2), 3) and 4) all require api changes, which is less likely we can do now.
1) seems more doable.

**Comment by Random-Liu** [comment]
@qiujian16 We recently removed the grpc layer in between CRI-containerd and containerd (https://github.com/containerd/cri/pull/658), so this won't be a problem anymore for the v1.0.0-rc.0 release. So I'll remove this from our v1.0.0-rc.0 milestone.

However, when you run a lot of containers, `ctr` may still have this issue, which we may want to fix in containerd.

**Comment by qiujian16** [comment]
@Random-Liu thanks! We will try kubernetes 1.10 with the latest cri-containerd build later.

**Comment by Random-Liu** [comment]
I'll file an issue to containerd for the grpc message size limit. And I think we can close this one after that.

**Comment by Random-Liu** [comment]
Close this one in favor of https://github.com/containerd/containerd/issues/2226.
